modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="siege"
version="${file.jarVersion}"
displayName="Siege"
credits=""
authors="Snownee"
description='''
'''

[[dependencies.siege]]
    modId="kiwi"
    mandatory=true
    versionRange="[2.4.3,2.7)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.siege]]
    modId="fermion"
    mandatory=true
    versionRange="[1,2)"
    ordering="BEFORE"
    side="BOTH"