modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="siege"
version="${file.jarVersion}"
displayName="Siege"
credits="MalayP, BloCamLimb"
authors="Snownee"
description='''Huge thanks to my supporters:

粉鱼 Lioness131 皮蛋 路人玖 Cherls idyllic_bean 鱼加盐有点咸 洋葱菜菜子 面条公爵 车轮饼 mc00zhu 洛华 纪华裕 可爱至吉 ycccz 东篱下i Ruriri Meowsquito
'''

[[dependencies.siege]]
    modId="kiwi"
    mandatory=true
    versionRange="[2.4.3,2.7)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.siege]]
    modId="fermion"
    mandatory=true
    versionRange="[1,2)"
    ordering="BEFORE"
    side="BOTH"